`timescale 1ns / 1ps

module FIR(
clk_125,
rst,
x,
y,
pll_lock,
pll_clock
);

input clk_125,rst;
input[7:0] x;
output[7:0] y;
output pll_lock, pll_clock;

// These are the fixed coefficients for this filter 
//these following numbers are in Q(3,4) format
reg[7:0] a = 8; // 0.5  
reg[7:0] b = -24; //-1.5
reg[7:0] c = 32; //2.0

reg[7:0] x_1, x_2; 
wire[7:0] r0, r1, r2;

// 200MHz clock generation module 
clk_wiz_0 pll_inst_core (
  .clk_in1(clk_125),
  .clk_out1(pll_clock),
  .reset(~rst),
  .locked(pll_lock) // if locked = 1, the "clk" generated by the PLL is stable, else it is unstable
);

multiply m0(a,x,r0);
multiply m1(b,x_1,r1);
multiply m2(c,x_2,r2);

// y = a*x + b*x1 + c*x2;
assign y=r0+r1+r2;

always@(posedge pll_clock or negedge rst)begin
    if(~rst)begin
        x_1<=0;
        x_2<=0;
    end
    else begin
        x_1<=x;
        x_2<=x_1;
    end
end

endmodule
