`timescale 1ns / 1ps

module IIR(
clk,
rst,
x,
y,
pll_lock,
pll_clock
);

input clk,rst;
input[7:0] x;
//output reg [7:0] y;
output [7:0] y;
output pll_lock, pll_clock;

// These are the fixed coefficients for this filter
reg[7:0] a = 0.5*16; // 0.5
reg[7:0] b = 256 - 1.5*16; // -1.5
reg[7:0] c = 2*16; // 2
reg[7:0] d = 256 - 16; // -1


reg[7:0] x_1; 
reg[7:0] y_1,y_2;


/*************** Your code here ***************/
wire [7:0] r0, r1, r2, r3;
//reg [7:0] r0_reg, r1_reg, r2_reg, r3_reg;

// 200MHz clock generation module 
clk_wiz_0 pll_inst_core (
  .clk_in1(clk),
  .clk_out1(pll_clock),
  .reset(~rst),
  .locked(pll_lock) // if locked = 1, the "clk" generated by the PLL is stable, else it is unstable
);

multiply m0 (a, x, r0);
multiply m1 (b, x_1, r1);
multiply m2 (c, y_1, r2);
multiply m3 (d, y_2, r3);

// y = a*x + b*x1 + c*y1 + d*y2;
//assign y = r0_reg + r1_reg + r2_reg + r3_reg;
assign y = r0 + r1 + r2 + r3;

always @(posedge pll_clock or negedge rst) begin
    if(~rst) begin
//        r0<=0;
//        r1<=0;
//        r2<=0;
//        r3<=0;
        
        //y<=0;
        x_1<=0;
        y_1<=0;
        y_2<=0;
    end
    else begin
//        r0<=r0;
//        r1<=r1;
//        r2<=r2;
//        r3<=r3;
        
        //y <= r0_reg + r1_reg + r2_reg + r3_reg;
        x_1<=x; 
        y_1<=y;
        y_2<=y_1;
    end
end

/********************* Done *********************/


endmodule