# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/datatrans_sys/datatrans_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==datatrans_sys || ORIG_REF_NAME==datatrans_sys} -quiet] -quiet

# IP: bd/datatrans_sys/ip/datatrans_sys_processing_system7_0_0/datatrans_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==datatrans_sys_processing_system7_0_0 || ORIG_REF_NAME==datatrans_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/datatrans_sys/ip/datatrans_sys_auto_pc_0/datatrans_sys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==datatrans_sys_auto_pc_0 || ORIG_REF_NAME==datatrans_sys_auto_pc_0} -quiet] -quiet

# IP: bd/datatrans_sys/ip/datatrans_sys_processing_system7_0_axi_periph_0/datatrans_sys_processing_system7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==datatrans_sys_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==datatrans_sys_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/datatrans_sys/ip/datatrans_sys_rst_processing_system7_0_100M_0/datatrans_sys_rst_processing_system7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==datatrans_sys_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==datatrans_sys_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: bd/datatrans_sys/ip/datatrans_sys_trans_0_0/datatrans_sys_trans_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==datatrans_sys_trans_0_0 || ORIG_REF_NAME==datatrans_sys_trans_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/bd/datatrans_sys/ip/datatrans_sys_processing_system7_0_0/datatrans_sys_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==datatrans_sys_processing_system7_0_0 || ORIG_REF_NAME==datatrans_sys_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/bd/datatrans_sys/ip/datatrans_sys_auto_pc_0/datatrans_sys_auto_pc_0_ooc.xdc

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/bd/datatrans_sys/ip/datatrans_sys_rst_processing_system7_0_100M_0/datatrans_sys_rst_processing_system7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==datatrans_sys_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==datatrans_sys_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/bd/datatrans_sys/ip/datatrans_sys_rst_processing_system7_0_100M_0/datatrans_sys_rst_processing_system7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==datatrans_sys_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==datatrans_sys_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/bd/datatrans_sys/ip/datatrans_sys_rst_processing_system7_0_100M_0/datatrans_sys_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/bd/datatrans_sys/datatrans_sys_ooc.xdc

# XDC: /home/grads/t/tamu_vik/ECEN-722/lab8/lab8_base/base/base.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
