#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 02 18:05:56 CDT 2025
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim IIR_fold_tb_behav -key {Behavioral:sim_1:Functional:IIR_fold_tb} -tclbatch IIR_fold_tb.tcl -protoinst "protoinst_files/datatrans_sys.protoinst" -log simulate.log"
xsim IIR_fold_tb_behav -key {Behavioral:sim_1:Functional:IIR_fold_tb} -tclbatch IIR_fold_tb.tcl -protoinst "protoinst_files/datatrans_sys.protoinst" -log simulate.log

